# Generated by Django 5.1.2 on 2024-11-04 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='start',
            new_name='star',
        ),
    ]
