# Generated by Django 5.1.2 on 2024-11-04 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_blog_created_at_blog_deleted_at_blog_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardcredit',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='cardcredit',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cardcredit',
            name='number',
        ),
        migrations.AddField(
            model_name='cardcredit',
            name='accepted',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardcredit',
            name='content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardcredit',
            name='transaction',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardcredit',
            name='valid_in',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
